package Gas;

import Gas.Home;
import Gas.Gas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
public class Informasi extends javax.swing.JFrame {
    private static Connection config;
    public Informasi() {
        this.setLocation(200, 100);
        initComponents();
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                DateFormat dateFormat1 = new SimpleDateFormat("HH : mm : ss");
                Date date1 = new Date();
                jLabel_Waktu.setText(dateFormat1.format(date1));
                DateFormat dateFormat2 = new SimpleDateFormat("dd");
                Date date2 = new Date();
                jLabel_Tanggal.setText(dateFormat2.format(date2));
                DateFormat dateFormat3 = new SimpleDateFormat("MMMMM");
                Date date3 = new Date();
                jLabel_Bulan.setText(dateFormat3.format(date3));
                DateFormat dateFormat4 = new SimpleDateFormat("yyyy");
                Date date4 = new Date();
                jLabel2.setText(dateFormat4.format(date4));
            }
        }, 0, 1000);
        try {       
            Connection c=connect();
            Statement s= c.createStatement();
            String sql="SELECT * FROM tb_gas WHERE stok_terisi=0 OR stok_terisi<=5 ORDER BY stok_terisi, nama, ukuran ASC";
            ResultSet r=s.executeQuery(sql);        
            while (r.next()) {
                String notif1="",notif2="";
                if(r.getString("stok_terisi").equals("0")){
                    notif1="  - "+r.getString("nama")+" "+r.getString("ukuran")+"Kg\n";                    
                }else{
                    notif2="  - "+r.getString("nama")+" "+r.getString("ukuran")+"Kg tinggal "+r.getString("stok_terisi")+"\n";   
                }
                this.jTextArea_habis.append(notif1);
                this.jTextArea_akanhabis.append(notif2);
            }
            r.close();
            s.close();
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
        }
    }
    private static Connection connect() {
        if (config==null) {
            try {
                String url="jdbc:mysql://localhost:3306/db_khiqma";
                String user="root"; 
                String password="";
                DriverManager.registerDriver(new com.mysql.jdbc.Driver());
                config=DriverManager.getConnection(url,user,password);

            }catch (SQLException x) {
                System.out.println("Connection Error");
            }
        }
        return config;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel_Top = new javax.swing.JPanel();
        jPanel_Exit = new javax.swing.JPanel();
        jButton_Exit = new javax.swing.JButton();
        jLabel_Title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Menu = new javax.swing.JLabel();
        jPanel_Menu = new javax.swing.JPanel();
        jPanel_Mn1 = new javax.swing.JPanel();
        jLabel_Mn1 = new javax.swing.JLabel();
        jPanel_Mn2 = new javax.swing.JPanel();
        jLabel_Mn2 = new javax.swing.JLabel();
        jPanel_Mn3 = new javax.swing.JPanel();
        jLabel_Mn3 = new javax.swing.JLabel();
        jPanel_Mn4 = new javax.swing.JPanel();
        jLabel_Mn4 = new javax.swing.JLabel();
        jPanel_Mn5 = new javax.swing.JPanel();
        jLabel_Mn5 = new javax.swing.JLabel();
        jLabel_Waktu = new javax.swing.JLabel();
        jLabel_Tanggal = new javax.swing.JLabel();
        jLabel_Bulan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Mn6 = new javax.swing.JPanel();
        jLabel_Mn6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_habis = new javax.swing.JTextArea();
        label3 = new java.awt.Label();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_akanhabis = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        jPanel_Top.setBackground(new java.awt.Color(0, 102, 51));

        jPanel_Exit.setBackground(new java.awt.Color(0, 102, 51));

        jButton_Exit.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Exit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_Exit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Exit.setText("x");
        jButton_Exit.setBorder(null);
        jButton_Exit.setContentAreaFilled(false);
        jButton_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_Exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_ExitMouseExited(evt);
            }
        });
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ExitLayout = new javax.swing.GroupLayout(jPanel_Exit);
        jPanel_Exit.setLayout(jPanel_ExitLayout);
        jPanel_ExitLayout.setHorizontalGroup(
            jPanel_ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_ExitLayout.setVerticalGroup(
            jPanel_ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel_Title.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Title.setText("Aplikasi Khiqma Gas");

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Khiqma Project\\Khiqma\\img\\1 icon.png")); // NOI18N

        javax.swing.GroupLayout jPanel_TopLayout = new javax.swing.GroupLayout(jPanel_Top);
        jPanel_Top.setLayout(jPanel_TopLayout);
        jPanel_TopLayout.setHorizontalGroup(
            jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TopLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_TopLayout.setVerticalGroup(
            jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel_Menu.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Menu.setForeground(new java.awt.Color(0, 102, 51));
        jLabel_Menu.setIcon(new javax.swing.ImageIcon("E:\\Khiqma Project\\Khiqma\\img\\2 icon.png")); // NOI18N
        jLabel_Menu.setText("  Menu");
        jLabel_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        jPanel_Menu.setBackground(new java.awt.Color(0, 102, 51));
        jPanel_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        jPanel_Mn1.setBackground(new java.awt.Color(0, 102, 51));

        jLabel_Mn1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Mn1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mn1.setIcon(new javax.swing.ImageIcon("E:\\Khiqma Project\\Khiqma\\img\\menu1.png")); // NOI18N
        jLabel_Mn1.setText("  Gas");
        jLabel_Mn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Mn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Mn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Mn1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Mn1Layout = new javax.swing.GroupLayout(jPanel_Mn1);
        jPanel_Mn1.setLayout(jPanel_Mn1Layout);
        jPanel_Mn1Layout.setHorizontalGroup(
            jPanel_Mn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Mn1Layout.setVerticalGroup(
            jPanel_Mn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_Mn2.setBackground(new java.awt.Color(0, 102, 51));

        jLabel_Mn2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Mn2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mn2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Khiqma Project/Khiqma/img/menu2.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel_Mn2.setText("  Transaksi");
        jLabel_Mn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Mn2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Mn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Mn2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Mn2Layout = new javax.swing.GroupLayout(jPanel_Mn2);
        jPanel_Mn2.setLayout(jPanel_Mn2Layout);
        jPanel_Mn2Layout.setHorizontalGroup(
            jPanel_Mn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Mn2Layout.setVerticalGroup(
            jPanel_Mn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Mn2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Mn2))
        );

        jPanel_Mn3.setBackground(new java.awt.Color(0, 102, 51));

        jLabel_Mn3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Mn3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mn3.setIcon(new javax.swing.ImageIcon("E:\\Khiqma Project\\Khiqma\\img\\menu3.png")); // NOI18N
        jLabel_Mn3.setText("  Penghasilan");
        jLabel_Mn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Mn3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Mn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Mn3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Mn3Layout = new javax.swing.GroupLayout(jPanel_Mn3);
        jPanel_Mn3.setLayout(jPanel_Mn3Layout);
        jPanel_Mn3Layout.setHorizontalGroup(
            jPanel_Mn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );
        jPanel_Mn3Layout.setVerticalGroup(
            jPanel_Mn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Mn3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Mn3))
        );

        jPanel_Mn4.setBackground(new java.awt.Color(0, 102, 51));

        jLabel_Mn4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Mn4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mn4.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Khiqma Project/Khiqma/img/menu0.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel_Mn4.setText("  Beranda");
        jLabel_Mn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Mn4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Mn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Mn4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Mn4Layout = new javax.swing.GroupLayout(jPanel_Mn4);
        jPanel_Mn4.setLayout(jPanel_Mn4Layout);
        jPanel_Mn4Layout.setHorizontalGroup(
            jPanel_Mn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Mn4Layout.setVerticalGroup(
            jPanel_Mn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_Mn5.setBackground(new java.awt.Color(0, 102, 51));

        jLabel_Mn5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Mn5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mn5.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Khiqma Project/Khiqma/img/menu5.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel_Mn5.setText("  Keluar");
        jLabel_Mn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Mn5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Mn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Mn5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Mn5Layout = new javax.swing.GroupLayout(jPanel_Mn5);
        jPanel_Mn5.setLayout(jPanel_Mn5Layout);
        jPanel_Mn5Layout.setHorizontalGroup(
            jPanel_Mn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Mn5Layout.setVerticalGroup(
            jPanel_Mn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Mn5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Mn5))
        );

        jLabel_Waktu.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Waktu.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Waktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Waktu.setText("10 : 10 : 10");

        jLabel_Tanggal.setFont(new java.awt.Font("Century Gothic", 0, 38)); // NOI18N
        jLabel_Tanggal.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Tanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Tanggal.setText("12");

        jLabel_Bulan.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Bulan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Bulan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Bulan.setText("January");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("2016");

        jPanel_Mn6.setBackground(new java.awt.Color(112, 195, 155));

        jLabel_Mn6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Mn6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mn6.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Khiqma Project/Khiqma/img/menu6.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel_Mn6.setText("  Informasi");
        jLabel_Mn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Mn6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Mn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Mn6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Mn6Layout = new javax.swing.GroupLayout(jPanel_Mn6);
        jPanel_Mn6.setLayout(jPanel_Mn6Layout);
        jPanel_Mn6Layout.setHorizontalGroup(
            jPanel_Mn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Mn6Layout.setVerticalGroup(
            jPanel_Mn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Mn6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Mn6))
        );

        javax.swing.GroupLayout jPanel_MenuLayout = new javax.swing.GroupLayout(jPanel_Menu);
        jPanel_Menu.setLayout(jPanel_MenuLayout);
        jPanel_MenuLayout.setHorizontalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Mn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Mn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Mn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Mn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addComponent(jLabel_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Bulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Waktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel_Mn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Mn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_MenuLayout.setVerticalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Mn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Mn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Mn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Mn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Mn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Mn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(0, 102, 51));
        label1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Informasi");

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(34, 142, 89));
        label2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Tabung Gas Habis");

        jTextArea_habis.setColumns(10);
        jTextArea_habis.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextArea_habis.setRows(5);
        jTextArea_habis.setTabSize(10);
        jTextArea_habis.setAutoscrolls(false);
        jTextArea_habis.setBorder(null);
        jTextArea_habis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTextArea_habis);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(34, 142, 89));
        label3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("Tabung Gas Akan Habis");

        jTextArea_akanhabis.setColumns(10);
        jTextArea_akanhabis.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTextArea_akanhabis.setRows(5);
        jTextArea_akanhabis.setTabSize(10);
        jTextArea_akanhabis.setAutoscrolls(false);
        jTextArea_akanhabis.setBorder(null);
        jTextArea_akanhabis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(jTextArea_akanhabis);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(label2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                            .addComponent(label3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel_Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_Menu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ExitMouseExited
        jPanel_Exit.setBackground(new java.awt.Color(0, 102, 51));
        jButton_Exit.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jButton_ExitMouseExited

    private void jButton_ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ExitMouseEntered
        // TODO add your handling code here:
        jPanel_Exit.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Exit.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jButton_ExitMouseEntered

    private void jLabel_Mn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn1MouseEntered
        jPanel_Mn1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Mn1.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jLabel_Mn1MouseEntered

    private void jLabel_Mn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn2MouseEntered
        jPanel_Mn2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Mn2.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jLabel_Mn2MouseEntered

    private void jLabel_Mn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn3MouseEntered
        jPanel_Mn3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Mn3.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jLabel_Mn3MouseEntered

    private void jLabel_Mn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn1MouseExited
        jPanel_Mn1.setBackground(new java.awt.Color(0, 102, 51));
        jLabel_Mn1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_Mn1MouseExited

    private void jLabel_Mn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn2MouseExited
        jPanel_Mn2.setBackground(new java.awt.Color(0, 102, 51));
        jLabel_Mn2.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_Mn2MouseExited

    private void jLabel_Mn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn3MouseExited
        jPanel_Mn3.setBackground(new java.awt.Color(0, 102, 51));
        jLabel_Mn3.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_Mn3MouseExited

    private void jLabel_Mn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn4MouseEntered
        jPanel_Mn4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Mn4.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jLabel_Mn4MouseEntered

    private void jLabel_Mn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn4MouseExited
        jPanel_Mn4.setBackground(new java.awt.Color(0, 102, 51));
        jLabel_Mn4.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_Mn4MouseExited

    private void jLabel_Mn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn5MouseEntered
        jPanel_Mn5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Mn5.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jLabel_Mn5MouseEntered

    private void jLabel_Mn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn5MouseExited
        jPanel_Mn5.setBackground(new java.awt.Color(0, 102, 51));
        jLabel_Mn5.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_Mn5MouseExited

    private void jLabel_Mn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_Mn5MouseClicked

    private void jLabel_Mn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn4MouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_Mn4MouseClicked

    private void jLabel_Mn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn2MouseClicked
        Transaksi tr = new Transaksi();
        tr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_Mn2MouseClicked

    private void jLabel_Mn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn1MouseClicked
        Gas gs = new Gas();
        gs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_Mn1MouseClicked

    private void jLabel_Mn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_Mn6MouseClicked

    private void jLabel_Mn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn6MouseEntered
        jPanel_Mn6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Mn6.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jLabel_Mn6MouseEntered

    private void jLabel_Mn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn6MouseExited
        jPanel_Mn6.setBackground(new java.awt.Color(112,195,155));
        jLabel_Mn6.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_Mn6MouseExited

    private void jLabel_Mn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn3MouseClicked
        Penghasilan peng = new Penghasilan();
        peng.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_Mn3MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Bulan;
    private javax.swing.JLabel jLabel_Menu;
    private javax.swing.JLabel jLabel_Mn1;
    private javax.swing.JLabel jLabel_Mn2;
    private javax.swing.JLabel jLabel_Mn3;
    private javax.swing.JLabel jLabel_Mn4;
    private javax.swing.JLabel jLabel_Mn5;
    private javax.swing.JLabel jLabel_Mn6;
    private javax.swing.JLabel jLabel_Tanggal;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_Waktu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_Exit;
    private javax.swing.JPanel jPanel_Menu;
    private javax.swing.JPanel jPanel_Mn1;
    private javax.swing.JPanel jPanel_Mn2;
    private javax.swing.JPanel jPanel_Mn3;
    private javax.swing.JPanel jPanel_Mn4;
    private javax.swing.JPanel jPanel_Mn5;
    private javax.swing.JPanel jPanel_Mn6;
    private javax.swing.JPanel jPanel_Top;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea_akanhabis;
    private javax.swing.JTextArea jTextArea_habis;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
