package Gas;

import Gas.Transaksi;
import Gas.Informasi;
import Gas.Home;
import Gas.Gas;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.paint.Color;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.util.HSSFColor;
public class Penghasilan extends javax.swing.JFrame {
    private static Connection config;
    String sql;
    String tgl="",bln="",thn="";
    String tgl1="",tgl2="";
    int pengeluaran=0,pemasukan=0;
    public Penghasilan() {
        this.setLocation(200, 100);
        initComponents();
        Timer timer = new Timer();
        DateFormat dateFormat2 = new SimpleDateFormat("dd");
        Date date2 = new Date();
        jLabel_Tanggal.setText(dateFormat2.format(date2));
        tgl=dateFormat2.format(date2);
        DateFormat dateFormat3 = new SimpleDateFormat("MMMMM");
        Date date3 = new Date();
        jLabel_Bulan.setText(dateFormat3.format(date3));
        DateFormat dateFormat4 = new SimpleDateFormat("yyyy");
        Date date4 = new Date();
        jLabel2.setText(dateFormat4.format(date4));
        thn=dateFormat4.format(date4);
        DateFormat dateFormat5 = new SimpleDateFormat("MM");
        Date date5 = new Date();
        bln=dateFormat5.format(date5);
        timer.scheduleAtFixedRate(new TimerTask() {
            public void run() {
                DateFormat dateFormat1 = new SimpleDateFormat("HH : mm : ss");
                Date date1 = new Date();
                jLabel_Waktu.setText(dateFormat1.format(date1));
            }
        }, 0, 1000);
        this.tgl_awal.setText(tgl+"-"+bln+"-"+thn);
        this.tgl_akhir.setText(tgl+"-"+bln+"-"+thn);
        try {       
            Connection c=connect();
            Statement s= c.createStatement();
            String sql1="SELECT count(id_transaksi) as jumlah  FROM `tb_transaksi` WHERE "
                    + "(`waktu` > '"+thn+"-01-01 00:00:00' AND `waktu` < '"+thn+"-12-31 24:60:60') AND (jns_transaksi='Jual Grosir' OR jns_transaksi='Jual Eceran') ";
            ResultSet r1=s.executeQuery(sql1);        
            while (r1.next()) {
                this.lbl_thn.setText(r1.getString("jumlah"));
            }
            String sql2="SELECT count(id_transaksi) as jumlah  FROM `tb_transaksi` WHERE "
                    + "(`waktu` > '"+thn+"-"+bln+"-01 00:00:00' AND `waktu` < '"+thn+"-"+bln+"-31 24:60:60') AND (jns_transaksi='Jual Grosir' OR jns_transaksi='Jual Eceran') ";
            ResultSet r2=s.executeQuery(sql2);        
            while (r2.next()) {
                this.lbl_bln.setText(r2.getString("jumlah"));
            }
            String sql3="SELECT count(id_transaksi) as jumlah  FROM `tb_transaksi` WHERE "
                    + "(`waktu` > '"+thn+"-"+bln+"-"+tgl+" 00:00:00' AND `waktu` < '"+thn+"-"+bln+"-"+tgl+" 24:60:60') AND (jns_transaksi='Jual Grosir' OR jns_transaksi='Jual Eceran') ";
            ResultSet r3=s.executeQuery(sql3);        
            while (r3.next()) {
                this.lbl_tgl.setText(r3.getString("jumlah"));
            }
            r1.close(); r2.close(); r3.close();
            s.close();
        }catch(SQLException e) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan");
        }
    }
    private static Connection connect() {
        if (config==null) {
            try {
                String url="jdbc:mysql://localhost:3306/db_khiqma";
                String user="root"; 
                String password="";
                DriverManager.registerDriver(new com.mysql.jdbc.Driver());
                config=DriverManager.getConnection(url,user,password);

            }catch (SQLException x) {
                System.out.println("Connection Error");
            }
        }
        return config;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel_Top = new javax.swing.JPanel();
        jPanel_Exit = new javax.swing.JPanel();
        jButton_Exit = new javax.swing.JButton();
        jLabel_Title = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_Menu = new javax.swing.JLabel();
        jPanel_Menu = new javax.swing.JPanel();
        jPanel_Mn1 = new javax.swing.JPanel();
        jLabel_Mn1 = new javax.swing.JLabel();
        jPanel_Mn2 = new javax.swing.JPanel();
        jLabel_Mn2 = new javax.swing.JLabel();
        jPanel_Mn3 = new javax.swing.JPanel();
        jLabel_Mn3 = new javax.swing.JLabel();
        jPanel_Mn4 = new javax.swing.JPanel();
        jLabel_Mn4 = new javax.swing.JLabel();
        jPanel_Mn5 = new javax.swing.JPanel();
        jLabel_Mn5 = new javax.swing.JLabel();
        jLabel_Waktu = new javax.swing.JLabel();
        jLabel_Tanggal = new javax.swing.JLabel();
        jLabel_Bulan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Mn6 = new javax.swing.JPanel();
        jLabel_Mn6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        jPanel3 = new javax.swing.JPanel();
        label2 = new java.awt.Label();
        label5 = new java.awt.Label();
        label4 = new java.awt.Label();
        lbl_tgl = new java.awt.Label();
        lbl_thn = new java.awt.Label();
        lbl_bln = new java.awt.Label();
        label10 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        tgl_awal = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        tgl_akhir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        jPanel_Top.setBackground(new java.awt.Color(0, 102, 51));

        jPanel_Exit.setBackground(new java.awt.Color(0, 102, 51));

        jButton_Exit.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Exit.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton_Exit.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Exit.setText("x");
        jButton_Exit.setBorder(null);
        jButton_Exit.setContentAreaFilled(false);
        jButton_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_Exit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_ExitMouseExited(evt);
            }
        });
        jButton_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ExitLayout = new javax.swing.GroupLayout(jPanel_Exit);
        jPanel_Exit.setLayout(jPanel_ExitLayout);
        jPanel_ExitLayout.setHorizontalGroup(
            jPanel_ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_ExitLayout.setVerticalGroup(
            jPanel_ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel_Title.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel_Title.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Title.setText("Aplikasi Khiqma Gas");

        jLabel3.setIcon(new javax.swing.ImageIcon("E:\\Khiqma Project\\Khiqma\\img\\1 icon.png")); // NOI18N

        javax.swing.GroupLayout jPanel_TopLayout = new javax.swing.GroupLayout(jPanel_Top);
        jPanel_Top.setLayout(jPanel_TopLayout);
        jPanel_TopLayout.setHorizontalGroup(
            jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TopLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_TopLayout.setVerticalGroup(
            jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel_TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel_Menu.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Menu.setForeground(new java.awt.Color(0, 102, 51));
        jLabel_Menu.setIcon(new javax.swing.ImageIcon("E:\\Khiqma Project\\Khiqma\\img\\2 icon.png")); // NOI18N
        jLabel_Menu.setText("  Menu");
        jLabel_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        jPanel_Menu.setBackground(new java.awt.Color(0, 102, 51));
        jPanel_Menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        jPanel_Mn1.setBackground(new java.awt.Color(0, 102, 51));

        jLabel_Mn1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Mn1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mn1.setIcon(new javax.swing.ImageIcon("E:\\Khiqma Project\\Khiqma\\img\\menu1.png")); // NOI18N
        jLabel_Mn1.setText("  Gas");
        jLabel_Mn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Mn1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Mn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Mn1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Mn1Layout = new javax.swing.GroupLayout(jPanel_Mn1);
        jPanel_Mn1.setLayout(jPanel_Mn1Layout);
        jPanel_Mn1Layout.setHorizontalGroup(
            jPanel_Mn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Mn1Layout.setVerticalGroup(
            jPanel_Mn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_Mn2.setBackground(new java.awt.Color(0, 102, 51));

        jLabel_Mn2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Mn2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mn2.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Khiqma Project/Khiqma/img/menu2.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel_Mn2.setText("  Transaksi");
        jLabel_Mn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Mn2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Mn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Mn2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Mn2Layout = new javax.swing.GroupLayout(jPanel_Mn2);
        jPanel_Mn2.setLayout(jPanel_Mn2Layout);
        jPanel_Mn2Layout.setHorizontalGroup(
            jPanel_Mn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Mn2Layout.setVerticalGroup(
            jPanel_Mn2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Mn2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Mn2))
        );

        jPanel_Mn3.setBackground(new java.awt.Color(112, 195, 155));

        jLabel_Mn3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Mn3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mn3.setIcon(new javax.swing.ImageIcon("E:\\Khiqma Project\\Khiqma\\img\\menu3.png")); // NOI18N
        jLabel_Mn3.setText("  Penghasilan");
        jLabel_Mn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Mn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Mn3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Mn3Layout = new javax.swing.GroupLayout(jPanel_Mn3);
        jPanel_Mn3.setLayout(jPanel_Mn3Layout);
        jPanel_Mn3Layout.setHorizontalGroup(
            jPanel_Mn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Mn3Layout.setVerticalGroup(
            jPanel_Mn3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Mn3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Mn3))
        );

        jPanel_Mn4.setBackground(new java.awt.Color(0, 102, 51));

        jLabel_Mn4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Mn4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mn4.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Khiqma Project/Khiqma/img/menu0.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel_Mn4.setText("  Beranda");
        jLabel_Mn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Mn4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Mn4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Mn4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Mn4Layout = new javax.swing.GroupLayout(jPanel_Mn4);
        jPanel_Mn4.setLayout(jPanel_Mn4Layout);
        jPanel_Mn4Layout.setHorizontalGroup(
            jPanel_Mn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Mn4Layout.setVerticalGroup(
            jPanel_Mn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel_Mn5.setBackground(new java.awt.Color(0, 102, 51));

        jLabel_Mn5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Mn5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mn5.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Khiqma Project/Khiqma/img/menu5.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel_Mn5.setText("  Keluar");
        jLabel_Mn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Mn5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Mn5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Mn5MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Mn5Layout = new javax.swing.GroupLayout(jPanel_Mn5);
        jPanel_Mn5.setLayout(jPanel_Mn5Layout);
        jPanel_Mn5Layout.setHorizontalGroup(
            jPanel_Mn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Mn5Layout.setVerticalGroup(
            jPanel_Mn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Mn5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Mn5))
        );

        jLabel_Waktu.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Waktu.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Waktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Waktu.setText("10 : 10 : 10");

        jLabel_Tanggal.setFont(new java.awt.Font("Century Gothic", 0, 38)); // NOI18N
        jLabel_Tanggal.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Tanggal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_Tanggal.setText("12");

        jLabel_Bulan.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Bulan.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Bulan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel_Bulan.setText("January");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("2016");

        jPanel_Mn6.setBackground(new java.awt.Color(0, 102, 51));

        jLabel_Mn6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel_Mn6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mn6.setIcon(new javax.swing.JLabel() {
            public javax.swing.Icon getIcon() {
                try {
                    return new javax.swing.ImageIcon(
                        new java.net.URL("file:/E:/Khiqma Project/Khiqma/img/menu6.png")
                    );
                } catch (java.net.MalformedURLException e) {
                }
                return null;
            }
        }.getIcon());
        jLabel_Mn6.setText("  Informasi");
        jLabel_Mn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Mn6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_Mn6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_Mn6MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Mn6Layout = new javax.swing.GroupLayout(jPanel_Mn6);
        jPanel_Mn6.setLayout(jPanel_Mn6Layout);
        jPanel_Mn6Layout.setHorizontalGroup(
            jPanel_Mn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Mn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_Mn6Layout.setVerticalGroup(
            jPanel_Mn6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Mn6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Mn6))
        );

        javax.swing.GroupLayout jPanel_MenuLayout = new javax.swing.GroupLayout(jPanel_Menu);
        jPanel_Menu.setLayout(jPanel_MenuLayout);
        jPanel_MenuLayout.setHorizontalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Mn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Mn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Mn3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Mn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addComponent(jLabel_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Bulan, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Waktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel_Mn6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Mn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel_MenuLayout.setVerticalGroup(
            jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Mn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Mn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Mn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Mn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Mn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_Mn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_Tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel_Bulan, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(0, 102, 51));
        label1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Laporan Penghasilan");

        jPanel3.setBackground(new java.awt.Color(225, 225, 225));

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setBackground(new java.awt.Color(34, 142, 89));
        label2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("Per Hari");

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setBackground(new java.awt.Color(34, 142, 89));
        label5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("Per Tahun");

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setBackground(new java.awt.Color(34, 142, 89));
        label4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label4.setForeground(new java.awt.Color(255, 255, 255));
        label4.setText("Per Bulan");

        lbl_tgl.setAlignment(java.awt.Label.CENTER);
        lbl_tgl.setBackground(new java.awt.Color(255, 255, 255));
        lbl_tgl.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        lbl_tgl.setForeground(new java.awt.Color(0, 102, 51));
        lbl_tgl.setText("20");

        lbl_thn.setAlignment(java.awt.Label.CENTER);
        lbl_thn.setBackground(new java.awt.Color(255, 255, 255));
        lbl_thn.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        lbl_thn.setForeground(new java.awt.Color(0, 102, 51));
        lbl_thn.setText("20");

        lbl_bln.setAlignment(java.awt.Label.CENTER);
        lbl_bln.setBackground(new java.awt.Color(255, 255, 255));
        lbl_bln.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
        lbl_bln.setForeground(new java.awt.Color(0, 102, 51));
        lbl_bln.setText("20");

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setBackground(new java.awt.Color(34, 142, 89));
        label10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label10.setForeground(new java.awt.Color(255, 255, 255));
        label10.setText("Jumlah Penjualan Tabung Gas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label10, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(160, 160, 160)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_bln, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_thn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_thn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_bln, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setBackground(new java.awt.Color(0, 102, 51));
        label6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("Cetak");
        label6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label6MouseClicked(evt);
            }
        });

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setBackground(new java.awt.Color(34, 142, 89));
        label7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        label7.setForeground(new java.awt.Color(255, 255, 255));
        label7.setText("Cetak Laporan Transaksi");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sampai Dengan");

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        tgl_awal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tgl_awal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tgl_awal.setBorder(null);
        tgl_awal.setSelectionColor(new java.awt.Color(102, 102, 102));
        tgl_awal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tgl_awalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tgl_awalKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tgl_awal, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tgl_awal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));

        tgl_akhir.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        tgl_akhir.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tgl_akhir.setBorder(null);
        tgl_akhir.setSelectionColor(new java.awt.Color(102, 102, 102));
        tgl_akhir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tgl_akhirKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tgl_akhirKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tgl_akhir, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tgl_akhir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel_Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel_Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel_Menu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel_Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 46, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton_ExitActionPerformed

    private void jButton_ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ExitMouseExited
        jPanel_Exit.setBackground(new java.awt.Color(0, 102, 51));
        jButton_Exit.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jButton_ExitMouseExited

    private void jButton_ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ExitMouseEntered
        // TODO add your handling code here:
        jPanel_Exit.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Exit.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jButton_ExitMouseEntered

    private void jLabel_Mn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn1MouseEntered
        jPanel_Mn1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Mn1.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jLabel_Mn1MouseEntered

    private void jLabel_Mn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn2MouseEntered
        jPanel_Mn2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Mn2.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jLabel_Mn2MouseEntered

    private void jLabel_Mn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn3MouseEntered
        jPanel_Mn3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Mn3.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jLabel_Mn3MouseEntered

    private void jLabel_Mn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn1MouseExited
        jPanel_Mn1.setBackground(new java.awt.Color(0, 102, 51));
        jLabel_Mn1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_Mn1MouseExited

    private void jLabel_Mn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn2MouseExited
        jPanel_Mn2.setBackground(new java.awt.Color(0, 102, 51));
        jLabel_Mn2.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_Mn2MouseExited

    private void jLabel_Mn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn3MouseExited
        jPanel_Mn3.setBackground(new java.awt.Color(112,195,155));
        jLabel_Mn3.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_Mn3MouseExited

    private void jLabel_Mn4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn4MouseEntered
        jPanel_Mn4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Mn4.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jLabel_Mn4MouseEntered

    private void jLabel_Mn4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn4MouseExited
        jPanel_Mn4.setBackground(new java.awt.Color(0, 102, 51));
        jLabel_Mn4.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_Mn4MouseExited

    private void jLabel_Mn5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn5MouseEntered
        jPanel_Mn5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Mn5.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jLabel_Mn5MouseEntered

    private void jLabel_Mn5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn5MouseExited
        jPanel_Mn5.setBackground(new java.awt.Color(0, 102, 51));
        jLabel_Mn5.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_Mn5MouseExited

    private void jLabel_Mn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_Mn5MouseClicked

    private void jLabel_Mn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn4MouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_Mn4MouseClicked

    private void jLabel_Mn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn2MouseClicked
        Transaksi tr = new Transaksi();
        tr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_Mn2MouseClicked

    private void jLabel_Mn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn1MouseClicked
        Gas gs = new Gas();
        gs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_Mn1MouseClicked

    private void jLabel_Mn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn6MouseClicked
        Informasi in = new Informasi();
        in.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel_Mn6MouseClicked

    private void jLabel_Mn6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn6MouseEntered
        jPanel_Mn6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Mn6.setForeground(new java.awt.Color(0, 102, 51));
    }//GEN-LAST:event_jLabel_Mn6MouseEntered

    private void jLabel_Mn6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Mn6MouseExited
        jPanel_Mn6.setBackground(new java.awt.Color(0, 102, 51));
        jLabel_Mn6.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_jLabel_Mn6MouseExited

    private void label6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label6MouseClicked
        Timer timer = new Timer();
        DateFormat dateFormat1 = new SimpleDateFormat("dd");
        Date date1 = new Date();
        tgl=dateFormat1.format(date1);
        DateFormat dateFormat2 = new SimpleDateFormat("MM");
        Date date2 = new Date();
        bln=dateFormat2.format(date2);
        DateFormat dateFormat3 = new SimpleDateFormat("yyyy");
        Date date3 = new Date();
        thn=dateFormat3.format(date3);
        try {
            int i=0;
            Connection c=connect();
            Statement s= c.createStatement();
            HSSFWorkbook wb = new HSSFWorkbook();
            HSSFSheet sheet = wb.createSheet("New Sheet");
                    sql="SELECT * FROM `tb_transaksi` WHERE "
                        + "(`waktu` > '"+this.tgl_awal.getText().substring(6,10)+"-"+this.tgl_awal.getText().substring(3,5)+"-"+this.tgl_awal.getText().substring(0,2)+" 00:00:00' "
                            + "AND `waktu` < '"+this.tgl_akhir.getText().substring(6,10)+"-"+this.tgl_akhir.getText().substring(3,5)+"-"+this.tgl_akhir.getText().substring(0,2)+" 24:60:60') order by jns_transaksi,an_tmp ASC";
                    ResultSet r=s.executeQuery(sql);
                    
                    HSSFRow jud = sheet.createRow((short) i);i+=2;
                    HSSFCell cll;
                    cll = jud.createCell((short) 0);
                    cll.setCellValue("LAPORAN TRANSAKSI KHIQMA GAS");
                    
                    HSSFRow judul = sheet.createRow((short) i);i+=1;
                    HSSFCellStyle st = wb.createCellStyle();
                    st.setFillForegroundColor(HSSFColor.SEA_GREEN.index);
                    st.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);
                    HSSFCell cl;
                    cl = judul.createCell((short) 0);
                    cl.setCellValue("No.");
                    cl.setCellStyle(st);
                    cl = judul.createCell((short) 1);
                    cl.setCellValue("Atas Nama");
                    cl.setCellStyle(st);
                    cl = judul.createCell((short) 2);
                    cl.setCellValue("Jenis Transaksi");
                    cl.setCellStyle(st);
                    cl = judul.createCell((short) 3);
                    cl.setCellValue("Gas");
                    cl.setCellStyle(st);
                    cl = judul.createCell((short) 4);
                    cl.setCellValue("Jumlah");
                    cl.setCellStyle(st);
                    cl = judul.createCell((short) 5);
                    cl.setCellValue("Total Harga");
                    cl.setCellStyle(st);
                    int no=1;
                    while (r.next()) {
                        HSSFRow row = sheet.createRow((short) i);
                        HSSFCellStyle style = wb.createCellStyle();
                        HSSFCell cell;
                        cell = row.createCell((short) 0);
                        cell.setCellValue(no);no+=1;
                        cell.setCellStyle(style);
                        cell = row.createCell((short) 1);
                        cell.setCellValue(r.getString("an_tmp"));
                        cell.setCellStyle(style);
                        style = wb.createCellStyle();
                        cell = row.createCell((short) 2);
                        cell.setCellValue(r.getString("jns_transaksi"));
                        cell.setCellStyle(style);
                        cell = row.createCell((short) 3);
                        cell.setCellValue(r.getString("gas"));
                        cell.setCellStyle(style);
                        cell = row.createCell((short) 4);
                        cell.setCellValue(r.getInt("jml"));
                        cell.setCellStyle(style);
                        cell = row.createCell((short) 5);
                        cell.setCellValue(r.getInt("hrg"));
                        cell.setCellStyle(style);
                        if(r.getString("jns_transaksi").equals("Beli")){
                            pengeluaran+=r.getInt("hrg");
                        } else{
                            pemasukan+=r.getInt("hrg");
                        }
                        i+=1;
                    }
                    i+=1;
                    HSSFRow jj1 = sheet.createRow((short) i);i+=1;
                    HSSFCell cel1;
                    cel1 = jj1.createCell((short) 0);
                    cel1.setCellValue("Jumlah Pengeluaran");
                    cel1 = jj1.createCell((short) 5);
                    cel1.setCellValue(pengeluaran);
                    HSSFRow jj2 = sheet.createRow((short) i);
                    HSSFCell cel2;
                    cel2 = jj2.createCell((short) 0);
                    cel2.setCellValue("Jumlah Pemasukan");
                    cel2 = jj2.createCell((short) 5);
                    cel2.setCellValue(pemasukan);
            String namefile="Laporan.xls";
            FileOutputStream fileOut = new FileOutputStream(namefile);
            wb.write(fileOut);
            fileOut.close();
            JOptionPane.showMessageDialog(null, "File Excel Berhasil Dibuat");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "File Excel Gagal Dibuat");
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_label6MouseClicked

    private void tgl_awalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl_awalKeyReleased

    }//GEN-LAST:event_tgl_awalKeyReleased

    private void tgl_awalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl_awalKeyTyped

    }//GEN-LAST:event_tgl_awalKeyTyped

    private void tgl_akhirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl_akhirKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_akhirKeyReleased

    private void tgl_akhirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl_akhirKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_akhirKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penghasilan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_Bulan;
    private javax.swing.JLabel jLabel_Menu;
    private javax.swing.JLabel jLabel_Mn1;
    private javax.swing.JLabel jLabel_Mn2;
    private javax.swing.JLabel jLabel_Mn3;
    private javax.swing.JLabel jLabel_Mn4;
    private javax.swing.JLabel jLabel_Mn5;
    private javax.swing.JLabel jLabel_Mn6;
    private javax.swing.JLabel jLabel_Tanggal;
    private javax.swing.JLabel jLabel_Title;
    private javax.swing.JLabel jLabel_Waktu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Exit;
    private javax.swing.JPanel jPanel_Menu;
    private javax.swing.JPanel jPanel_Mn1;
    private javax.swing.JPanel jPanel_Mn2;
    private javax.swing.JPanel jPanel_Mn3;
    private javax.swing.JPanel jPanel_Mn4;
    private javax.swing.JPanel jPanel_Mn5;
    private javax.swing.JPanel jPanel_Mn6;
    private javax.swing.JPanel jPanel_Top;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label lbl_bln;
    private java.awt.Label lbl_tgl;
    private java.awt.Label lbl_thn;
    private javax.swing.JTextField tgl_akhir;
    private javax.swing.JTextField tgl_awal;
    // End of variables declaration//GEN-END:variables
}
